---
apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
type: Opaque
data:
  mongo: czBtM3MzY3IzdHA0c3N3MHJkIQ==
  flask: ODd3ZXJ5ZnVzZGhqdDY3cndlZnlnZGh3ZXJ0dTZ5Zmdkc2hid3J1dGV5ZmdzZGhi
  redis: NzZ0M3I0Z3l1ZTM0cnQ2N2VmZ3l1YmRoM2c2cmV3eXVyZmJo